# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
