# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20160307_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
